#application: tearautt-tiea2080-vt7
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: tiea2080/static

- url: /cron/.*
  script: main.app
  login: admin

- url: /task/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app
  login: required

